-- Migration to create request backup table for soft deletes
-- This table will store deleted requests instead of permanently removing them

CREATE TABLE IF NOT EXISTS requestbackup (
  id INT PRIMARY KEY,
  userId INT NOT NULL,
  vehicleId INT NOT NULL,
  vehicleNumber VARCHAR(50) NOT NULL,
  quantity INT NOT NULL,
  tubesQuantity INT NOT NULL,
  tireSize VARCHAR(50) NOT NULL,
  requestReason TEXT NOT NULL,
  requesterName VARCHAR(100) NOT NULL,
  requesterEmail VARCHAR(100) NOT NULL,
  requesterPhone VARCHAR(20) NOT NULL,
  vehicleBrand VARCHAR(50) NOT NULL,
  vehicleModel VARCHAR(50) NOT NULL,
  lastReplacementDate DATE NOT NULL,
  existingTireMake VARCHAR(100) NOT NULL,
  tireSizeRequired VARCHAR(50) NOT NULL,
  presentKmReading INT NOT NULL,
  previousKmReading INT NOT NULL,
  tireWearPattern VARCHAR(100) NOT NULL,
  comments TEXT,
  status ENUM(
    'pending',
    'supervisor approved',
    'technical-manager approved',
    'engineer approved',
    'customer-officer approved',
    'approved',
    'rejected',
    'supervisor rejected',
    'technical-manager rejected',
    'engineer rejected',
    'customer-officer rejected',
    'complete',
    'order placed',
    'order cancelled'
  ) DEFAULT 'pending',
  submittedAt DATETIME NOT NULL,
  supervisor_notes TEXT,
  technical_manager_note TEXT,
  engineer_note TEXT,
  customer_officer_note TEXT,
  supervisorId INT NOT NULL,
  technical_manager_id INT,
  supervisor_decision_by INT,
  engineer_decision_by INT,
  customer_officer_decision_by INT,
  deliveryOfficeName VARCHAR(100),
  deliveryStreetName VARCHAR(255),
  deliveryTown VARCHAR(100),
  totalPrice DECIMAL(10, 2),
  warrantyDistance INT,
  tireWearIndicatorAppeared BOOLEAN DEFAULT FALSE,
  Department VARCHAR(100),
  CostCenter VARCHAR(100),
  supplierName VARCHAR(255),
  supplierEmail VARCHAR(255),
  supplierPhone VARCHAR(255),
  orderNumber VARCHAR(255),
  orderNotes TEXT,
  orderPlacedDate DATETIME,
  deletedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deletedBy INT,
  INDEX idx_deleted_at (deletedAt),
  INDEX idx_original_id (id),
  INDEX idx_vehicle_number (vehicleNumber)
);